spring:
  datasource:
    url: jdbc:h2:file:~/restaurant
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: true
  h2:
    console:
      enabled: true
      path: /h2